--liquibase formatted sql
--changeset tkomarova:20220916000 create card table

CREATE TABLE card
(
    card_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(50),
    last_name     VARCHAR(50),
    number        VARCHAR(20) NOT NULL,
    pin           INT         NOT NULL,
    cvv           INT         NOT NULL,
    end_date      TIMESTAMP WITH TIME ZONE NOT NULL,
    active        BOOLEAN     NOT NULL,
    currency_type TEXT        NOT NULL
);

ALTER TABLE card
    ADD COLUMN card_template_id INT,
    ADD FOREIGN KEY (card_template_id) REFERENCES card_template (card_template_id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX idx_number ON card (number);

ALTER TABLE card ALTER COLUMN pin TYPE SMALLINT;

ALTER TABLE card ALTER COLUMN cvv TYPE SMALLINT;
