--liquibase formatted sql
--changeset tkomarova:20221013000 create bank account table

CREATE TABLE bank_account
(
    bank_account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iban            VARCHAR(30)              NOT NULL,
    balance         DECIMAL                  NOT NULL,
    currency_type   TEXT                     NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    active          BOOLEAN                  NOT NULL
);

ALTER TABLE bank_account
    ADD COLUMN card_id INT,
    ADD FOREIGN KEY (card_id) REFERENCES card (card_id)
        ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE bank_account
    ADD COLUMN customer_id INT,
    ADD FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
        ON UPDATE CASCADE ON DELETE SET NULL;
