--liquibase formatted sql
--changeset tkomarova:20220720000 create card_template table

CREATE TABLE card_template
(
    card_template_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL,
    issue_cost       FLOAT NOT NULL,
    service_cost     FLOAT NOT NULL,
    reissue_cost     FLOAT NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by_id    INT NOT NULL
);
